version: '3'
services:
  server1:
    build: ./my_app/
    image: my_app_image_composer
    hostname: server1
    container_name: server1_container
    ports:
      - 8081:8080
  server2:
    image: my_app_image_composer
    hostname: server2
    container_name: server2_container
    ports:
      - 8082:8080

  haproxy:
    build: ./haproxy/
    image: haproxy_image_composer
    hostname: haproxy
    container_name: haproxy_container
    ports:
      - 81:80